DROP TABLE IF EXISTS GAMESRATING;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USERGAMES;
DROP TABLE IF EXISTS USERLIBRARY;
DROP TABLE IF EXISTS USERRECOMMENDATIONS;

CREATE TABLE GAMESRATING(
	GAMEID INTEGER PRIMARY KEY, 
	LIKES INTEGER DEFAULT 0,
	DISLIKES INTEGER DEFAULT 0
);

CREATE TABLE "USER" (
	"ID"	INTEGER,
	"NAME"	TEXT NOT NULL,
	"PWD"	TEXT NOT NULL,
	"TIPO"	NUMERIC NOT NULL, 
    EMAIL TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE USERGAMES (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    GameId INTEGER NOT NULL,
    Liked BOOLEAN NOT NULL DEFAULT FALSE,
    Disliked BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (UserId, GameId),
    FOREIGN KEY (UserId) REFERENCES USER (Id)
);

CREATE TABLE USERLIBRARY (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    GameId INTEGER NOT NULL,
    Added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (UserId, GameId),
    FOREIGN KEY (UserId) REFERENCES USER (Id)
);

CREATE TABLE USERRECOMENDATIONS (
    ID INTEGER PRIMARY KEY,
    USERID INTEGER REFERENCES USER(ID),
	Mmorpg INTEGER,
    Shooter INTEGER,
    Strategy INTEGER,
    Moba INTEGER,
    Racing INTEGER,
    Sports INTEGER,
    Social INTEGER,
    Sandbox INTEGER,
    OpenWorld INTEGER,
    Survival INTEGER,
    Pvp INTEGER,
    Pve INTEGER,
    Pixel INTEGER,
    Voxel INTEGER,
    Zombie INTEGER,
    TurnBased INTEGER,
    FirstPerson INTEGER,
    ThirdPerson INTEGER,
    TopDown INTEGER,
    Tank INTEGER,
    Space INTEGER,
    Sailing INTEGER,
    SideScroller INTEGER,
    Superhero INTEGER,
    Permadeath INTEGER,
    Card INTEGER,
    BattleRoyale INTEGER,
    MMO INTEGER,
    MMOFPS INTEGER,
    MMOTPS INTEGER,
    Is3D INTEGER,
    Is2D INTEGER,
    Anime INTEGER,
    Fantasy INTEGER,
    SciFi INTEGER,
    Fighting INTEGER,
    ActionRPG INTEGER,
    Action INTEGER,
    Military INTEGER,
    MartialArts INTEGER,
    Flight INTEGER,
    LowSpec INTEGER,
    TowerDefense INTEGER,
    Horror INTEGER,
    MMORTS INTEGER
);